/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EvidenceRegistry {
  export type EvidenceStruct = {
    evidenceId: BytesLike;
    caseId: BytesLike;
    fileHash: BytesLike;
    fileURI: string;
    title: string;
    descriptionHash: BytesLike;
    evidenceType: BigNumberish;
    locationHash: BytesLike;
    collectedBy: AddressLike;
    currentOwner: AddressLike;
    collectedAt: BigNumberish;
    registeredAt: BigNumberish;
    status: BigNumberish;
    exists: boolean;
    isSensitive: boolean;
    custodyCount: BigNumberish;
    verificationCount: BigNumberish;
  };

  export type EvidenceStructOutput = [
    evidenceId: string,
    caseId: string,
    fileHash: string,
    fileURI: string,
    title: string,
    descriptionHash: string,
    evidenceType: bigint,
    locationHash: string,
    collectedBy: string,
    currentOwner: string,
    collectedAt: bigint,
    registeredAt: bigint,
    status: bigint,
    exists: boolean,
    isSensitive: boolean,
    custodyCount: bigint,
    verificationCount: bigint
  ] & {
    evidenceId: string;
    caseId: string;
    fileHash: string;
    fileURI: string;
    title: string;
    descriptionHash: string;
    evidenceType: bigint;
    locationHash: string;
    collectedBy: string;
    currentOwner: string;
    collectedAt: bigint;
    registeredAt: bigint;
    status: bigint;
    exists: boolean;
    isSensitive: boolean;
    custodyCount: bigint;
    verificationCount: bigint;
  };

  export type CustodyRecordStruct = {
    fromAddress: AddressLike;
    toAddress: AddressLike;
    previousStatus: BigNumberish;
    newStatus: BigNumberish;
    actionHash: BytesLike;
    timestamp: BigNumberish;
    txContext: BytesLike;
  };

  export type CustodyRecordStructOutput = [
    fromAddress: string,
    toAddress: string,
    previousStatus: bigint,
    newStatus: bigint,
    actionHash: string,
    timestamp: bigint,
    txContext: string
  ] & {
    fromAddress: string;
    toAddress: string;
    previousStatus: bigint;
    newStatus: bigint;
    actionHash: string;
    timestamp: bigint;
    txContext: string;
  };

  export type OfficerStruct = {
    wallet: AddressLike;
    nameHash: BytesLike;
    badgeHash: BytesLike;
    role: BytesLike;
    isActive: boolean;
    registeredAt: BigNumberish;
    evidenceCount: BigNumberish;
  };

  export type OfficerStructOutput = [
    wallet: string,
    nameHash: string,
    badgeHash: string,
    role: string,
    isActive: boolean,
    registeredAt: bigint,
    evidenceCount: bigint
  ] & {
    wallet: string;
    nameHash: string;
    badgeHash: string;
    role: string;
    isActive: boolean;
    registeredAt: bigint;
    evidenceCount: bigint;
  };

  export type TransferRequestStruct = {
    evidenceId: BytesLike;
    initiator: AddressLike;
    proposedOwner: AddressLike;
    reasonHash: BytesLike;
    createdAt: BigNumberish;
    approvalCount: BigNumberish;
    executed: boolean;
    cancelled: boolean;
    approvers: AddressLike[];
  };

  export type TransferRequestStructOutput = [
    evidenceId: string,
    initiator: string,
    proposedOwner: string,
    reasonHash: string,
    createdAt: bigint,
    approvalCount: bigint,
    executed: boolean,
    cancelled: boolean,
    approvers: string[]
  ] & {
    evidenceId: string;
    initiator: string;
    proposedOwner: string;
    reasonHash: string;
    createdAt: bigint;
    approvalCount: bigint;
    executed: boolean;
    cancelled: boolean;
    approvers: string[];
  };
}

export interface EvidenceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "AUDITOR_ROLE"
      | "INVESTIGATOR_ROLE"
      | "approveTransfer"
      | "batchVerifyEvidence"
      | "cancelTransferRequest"
      | "deactivateOfficer"
      | "evidenceCounter"
      | "executeTransfer"
      | "forceArchive"
      | "getEvidenceByCase"
      | "getEvidenceDetails"
      | "getEvidenceHistory"
      | "getEvidenceStatus"
      | "getOfficerDetails"
      | "getRoleOf"
      | "getTransferRequest"
      | "getVerificationLog"
      | "isFileHashRegistered"
      | "isRegistered"
      | "quickVerify"
      | "reactivateOfficer"
      | "registerEvidence"
      | "registerOfficer"
      | "requestTransfer"
      | "requiredApprovals"
      | "setRequiredApprovals"
      | "setSensitiveFlag"
      | "superAdmin"
      | "totalEvidenceCount"
      | "transferEvidence"
      | "transferSuperAdmin"
      | "updateEvidenceStatus"
      | "verifyEvidence"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EvidenceRegistered"
      | "EvidenceStatusUpdated"
      | "EvidenceTransferred"
      | "EvidenceVerified"
      | "OfficerDeactivated"
      | "OfficerRegistered"
      | "RequiredApprovalsUpdated"
      | "TransferRequestApproved"
      | "TransferRequestCancelled"
      | "TransferRequestCreated"
      | "TransferRequestExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVESTIGATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveTransfer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchVerifyEvidence",
    values: [BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTransferRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateOfficer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "evidenceCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransfer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "forceArchive",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidenceByCase",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidenceDetails",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidenceHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidenceStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOfficerDetails",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransferRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationLog",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFileHashRegistered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quickVerify",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateOfficer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEvidence",
    values: [
      BytesLike,
      BytesLike,
      string,
      string,
      BytesLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOfficer",
    values: [AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestTransfer",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredApprovals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRequiredApprovals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSensitiveFlag",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "superAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalEvidenceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferEvidence",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferSuperAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEvidenceStatus",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEvidence",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVESTIGATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchVerifyEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTransferRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateOfficer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evidenceCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceArchive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceByCase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOfficerDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRoleOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTransferRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFileHashRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quickVerify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactivateOfficer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOfficer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRequiredApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSensitiveFlag",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "superAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalEvidenceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferSuperAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEvidenceStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEvidence",
    data: BytesLike
  ): Result;
}

export namespace EvidenceRegisteredEvent {
  export type InputTuple = [
    evidenceId: BytesLike,
    caseId: BytesLike,
    fileHash: BytesLike,
    collectedBy: AddressLike,
    evidenceType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    evidenceId: string,
    caseId: string,
    fileHash: string,
    collectedBy: string,
    evidenceType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    evidenceId: string;
    caseId: string;
    fileHash: string;
    collectedBy: string;
    evidenceType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceStatusUpdatedEvent {
  export type InputTuple = [
    evidenceId: BytesLike,
    previousStatus: BigNumberish,
    newStatus: BigNumberish,
    updatedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    evidenceId: string,
    previousStatus: bigint,
    newStatus: bigint,
    updatedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    evidenceId: string;
    previousStatus: bigint;
    newStatus: bigint;
    updatedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceTransferredEvent {
  export type InputTuple = [
    evidenceId: BytesLike,
    fromOfficer: AddressLike,
    toOfficer: AddressLike,
    reasonHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    evidenceId: string,
    fromOfficer: string,
    toOfficer: string,
    reasonHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    evidenceId: string;
    fromOfficer: string;
    toOfficer: string;
    reasonHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceVerifiedEvent {
  export type InputTuple = [
    evidenceId: BytesLike,
    verifiedBy: AddressLike,
    isAuthentic: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    evidenceId: string,
    verifiedBy: string,
    isAuthentic: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    evidenceId: string;
    verifiedBy: string;
    isAuthentic: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfficerDeactivatedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    deactivatedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    deactivatedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    wallet: string;
    deactivatedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfficerRegisteredEvent {
  export type InputTuple = [
    wallet: AddressLike,
    role: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [wallet: string, role: string, timestamp: bigint];
  export interface OutputObject {
    wallet: string;
    role: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequiredApprovalsUpdatedEvent {
  export type InputTuple = [
    oldValue: BigNumberish,
    newValue: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldValue: bigint,
    newValue: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRequestApprovedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    approver: AddressLike,
    approvalCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    approver: string,
    approvalCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: string;
    approver: string;
    approvalCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRequestCancelledEvent {
  export type InputTuple = [
    requestId: BytesLike,
    cancelledBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    cancelledBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: string;
    cancelledBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRequestCreatedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    evidenceId: BytesLike,
    proposedOwner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    evidenceId: string,
    proposedOwner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: string;
    evidenceId: string;
    proposedOwner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRequestExecutedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    evidenceId: BytesLike,
    newOwner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    evidenceId: string,
    newOwner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: string;
    evidenceId: string;
    newOwner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EvidenceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EvidenceRegistry;
  waitForDeployment(): Promise<this>;

  interface: EvidenceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  AUDITOR_ROLE: TypedContractMethod<[], [string], "view">;

  INVESTIGATOR_ROLE: TypedContractMethod<[], [string], "view">;

  approveTransfer: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  batchVerifyEvidence: TypedContractMethod<
    [evidenceIds: BytesLike[], submittedHashes: BytesLike[]],
    [boolean[]],
    "nonpayable"
  >;

  cancelTransferRequest: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  deactivateOfficer: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  evidenceCounter: TypedContractMethod<[], [bigint], "view">;

  executeTransfer: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  forceArchive: TypedContractMethod<
    [evidenceId: BytesLike, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvidenceByCase: TypedContractMethod<
    [caseId: BytesLike],
    [string[]],
    "view"
  >;

  getEvidenceDetails: TypedContractMethod<
    [evidenceId: BytesLike],
    [EvidenceRegistry.EvidenceStructOutput],
    "view"
  >;

  getEvidenceHistory: TypedContractMethod<
    [evidenceId: BytesLike],
    [EvidenceRegistry.CustodyRecordStructOutput[]],
    "view"
  >;

  getEvidenceStatus: TypedContractMethod<
    [evidenceId: BytesLike],
    [
      [bigint, string, bigint] & {
        status: bigint;
        currentOwner: string;
        custodyCount: bigint;
      }
    ],
    "view"
  >;

  getOfficerDetails: TypedContractMethod<
    [wallet: AddressLike],
    [EvidenceRegistry.OfficerStructOutput],
    "view"
  >;

  getRoleOf: TypedContractMethod<[wallet: AddressLike], [string], "view">;

  getTransferRequest: TypedContractMethod<
    [requestId: BytesLike],
    [EvidenceRegistry.TransferRequestStructOutput],
    "view"
  >;

  getVerificationLog: TypedContractMethod<
    [evidenceId: BytesLike],
    [string[]],
    "view"
  >;

  isFileHashRegistered: TypedContractMethod<
    [fileHash: BytesLike],
    [boolean],
    "view"
  >;

  isRegistered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  quickVerify: TypedContractMethod<
    [evidenceId: BytesLike, fileHash: BytesLike],
    [boolean],
    "view"
  >;

  reactivateOfficer: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  registerEvidence: TypedContractMethod<
    [
      caseId: BytesLike,
      fileHash: BytesLike,
      fileURI: string,
      title: string,
      descriptionHash: BytesLike,
      evidenceType: BigNumberish,
      locationHash: BytesLike,
      collectedAt: BigNumberish,
      isSensitive: boolean
    ],
    [string],
    "nonpayable"
  >;

  registerOfficer: TypedContractMethod<
    [
      wallet: AddressLike,
      nameHash: BytesLike,
      badgeHash: BytesLike,
      role: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  requestTransfer: TypedContractMethod<
    [evidenceId: BytesLike, proposedOwner: AddressLike, reasonHash: BytesLike],
    [string],
    "nonpayable"
  >;

  requiredApprovals: TypedContractMethod<[], [bigint], "view">;

  setRequiredApprovals: TypedContractMethod<
    [newValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSensitiveFlag: TypedContractMethod<
    [evidenceId: BytesLike, sensitive: boolean],
    [void],
    "nonpayable"
  >;

  superAdmin: TypedContractMethod<[], [string], "view">;

  totalEvidenceCount: TypedContractMethod<[], [bigint], "view">;

  transferEvidence: TypedContractMethod<
    [evidenceId: BytesLike, toOfficer: AddressLike, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferSuperAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  updateEvidenceStatus: TypedContractMethod<
    [evidenceId: BytesLike, newStatus: BigNumberish, actionHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyEvidence: TypedContractMethod<
    [evidenceId: BytesLike, submittedHash: BytesLike],
    [
      [boolean, string, bigint] & {
        isAuthentic: boolean;
        registeredHash: string;
        registeredAt: bigint;
      }
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "AUDITOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVESTIGATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveTransfer"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchVerifyEvidence"
  ): TypedContractMethod<
    [evidenceIds: BytesLike[], submittedHashes: BytesLike[]],
    [boolean[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelTransferRequest"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateOfficer"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "evidenceCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeTransfer"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forceArchive"
  ): TypedContractMethod<
    [evidenceId: BytesLike, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEvidenceByCase"
  ): TypedContractMethod<[caseId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEvidenceDetails"
  ): TypedContractMethod<
    [evidenceId: BytesLike],
    [EvidenceRegistry.EvidenceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvidenceHistory"
  ): TypedContractMethod<
    [evidenceId: BytesLike],
    [EvidenceRegistry.CustodyRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvidenceStatus"
  ): TypedContractMethod<
    [evidenceId: BytesLike],
    [
      [bigint, string, bigint] & {
        status: bigint;
        currentOwner: string;
        custodyCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOfficerDetails"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [EvidenceRegistry.OfficerStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleOf"
  ): TypedContractMethod<[wallet: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTransferRequest"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [EvidenceRegistry.TransferRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerificationLog"
  ): TypedContractMethod<[evidenceId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isFileHashRegistered"
  ): TypedContractMethod<[fileHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "quickVerify"
  ): TypedContractMethod<
    [evidenceId: BytesLike, fileHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "reactivateOfficer"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerEvidence"
  ): TypedContractMethod<
    [
      caseId: BytesLike,
      fileHash: BytesLike,
      fileURI: string,
      title: string,
      descriptionHash: BytesLike,
      evidenceType: BigNumberish,
      locationHash: BytesLike,
      collectedAt: BigNumberish,
      isSensitive: boolean
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerOfficer"
  ): TypedContractMethod<
    [
      wallet: AddressLike,
      nameHash: BytesLike,
      badgeHash: BytesLike,
      role: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestTransfer"
  ): TypedContractMethod<
    [evidenceId: BytesLike, proposedOwner: AddressLike, reasonHash: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requiredApprovals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setRequiredApprovals"
  ): TypedContractMethod<[newValue: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSensitiveFlag"
  ): TypedContractMethod<
    [evidenceId: BytesLike, sensitive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "superAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalEvidenceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferEvidence"
  ): TypedContractMethod<
    [evidenceId: BytesLike, toOfficer: AddressLike, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferSuperAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateEvidenceStatus"
  ): TypedContractMethod<
    [evidenceId: BytesLike, newStatus: BigNumberish, actionHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyEvidence"
  ): TypedContractMethod<
    [evidenceId: BytesLike, submittedHash: BytesLike],
    [
      [boolean, string, bigint] & {
        isAuthentic: boolean;
        registeredHash: string;
        registeredAt: bigint;
      }
    ],
    "nonpayable"
  >;

  getEvent(
    key: "EvidenceRegistered"
  ): TypedContractEvent<
    EvidenceRegisteredEvent.InputTuple,
    EvidenceRegisteredEvent.OutputTuple,
    EvidenceRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceStatusUpdated"
  ): TypedContractEvent<
    EvidenceStatusUpdatedEvent.InputTuple,
    EvidenceStatusUpdatedEvent.OutputTuple,
    EvidenceStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceTransferred"
  ): TypedContractEvent<
    EvidenceTransferredEvent.InputTuple,
    EvidenceTransferredEvent.OutputTuple,
    EvidenceTransferredEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceVerified"
  ): TypedContractEvent<
    EvidenceVerifiedEvent.InputTuple,
    EvidenceVerifiedEvent.OutputTuple,
    EvidenceVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OfficerDeactivated"
  ): TypedContractEvent<
    OfficerDeactivatedEvent.InputTuple,
    OfficerDeactivatedEvent.OutputTuple,
    OfficerDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "OfficerRegistered"
  ): TypedContractEvent<
    OfficerRegisteredEvent.InputTuple,
    OfficerRegisteredEvent.OutputTuple,
    OfficerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RequiredApprovalsUpdated"
  ): TypedContractEvent<
    RequiredApprovalsUpdatedEvent.InputTuple,
    RequiredApprovalsUpdatedEvent.OutputTuple,
    RequiredApprovalsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRequestApproved"
  ): TypedContractEvent<
    TransferRequestApprovedEvent.InputTuple,
    TransferRequestApprovedEvent.OutputTuple,
    TransferRequestApprovedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRequestCancelled"
  ): TypedContractEvent<
    TransferRequestCancelledEvent.InputTuple,
    TransferRequestCancelledEvent.OutputTuple,
    TransferRequestCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TransferRequestCreated"
  ): TypedContractEvent<
    TransferRequestCreatedEvent.InputTuple,
    TransferRequestCreatedEvent.OutputTuple,
    TransferRequestCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRequestExecuted"
  ): TypedContractEvent<
    TransferRequestExecutedEvent.InputTuple,
    TransferRequestExecutedEvent.OutputTuple,
    TransferRequestExecutedEvent.OutputObject
  >;

  filters: {
    "EvidenceRegistered(bytes32,bytes32,bytes32,address,uint8,uint256)": TypedContractEvent<
      EvidenceRegisteredEvent.InputTuple,
      EvidenceRegisteredEvent.OutputTuple,
      EvidenceRegisteredEvent.OutputObject
    >;
    EvidenceRegistered: TypedContractEvent<
      EvidenceRegisteredEvent.InputTuple,
      EvidenceRegisteredEvent.OutputTuple,
      EvidenceRegisteredEvent.OutputObject
    >;

    "EvidenceStatusUpdated(bytes32,uint8,uint8,address,uint256)": TypedContractEvent<
      EvidenceStatusUpdatedEvent.InputTuple,
      EvidenceStatusUpdatedEvent.OutputTuple,
      EvidenceStatusUpdatedEvent.OutputObject
    >;
    EvidenceStatusUpdated: TypedContractEvent<
      EvidenceStatusUpdatedEvent.InputTuple,
      EvidenceStatusUpdatedEvent.OutputTuple,
      EvidenceStatusUpdatedEvent.OutputObject
    >;

    "EvidenceTransferred(bytes32,address,address,bytes32,uint256)": TypedContractEvent<
      EvidenceTransferredEvent.InputTuple,
      EvidenceTransferredEvent.OutputTuple,
      EvidenceTransferredEvent.OutputObject
    >;
    EvidenceTransferred: TypedContractEvent<
      EvidenceTransferredEvent.InputTuple,
      EvidenceTransferredEvent.OutputTuple,
      EvidenceTransferredEvent.OutputObject
    >;

    "EvidenceVerified(bytes32,address,bool,uint256)": TypedContractEvent<
      EvidenceVerifiedEvent.InputTuple,
      EvidenceVerifiedEvent.OutputTuple,
      EvidenceVerifiedEvent.OutputObject
    >;
    EvidenceVerified: TypedContractEvent<
      EvidenceVerifiedEvent.InputTuple,
      EvidenceVerifiedEvent.OutputTuple,
      EvidenceVerifiedEvent.OutputObject
    >;

    "OfficerDeactivated(address,address,uint256)": TypedContractEvent<
      OfficerDeactivatedEvent.InputTuple,
      OfficerDeactivatedEvent.OutputTuple,
      OfficerDeactivatedEvent.OutputObject
    >;
    OfficerDeactivated: TypedContractEvent<
      OfficerDeactivatedEvent.InputTuple,
      OfficerDeactivatedEvent.OutputTuple,
      OfficerDeactivatedEvent.OutputObject
    >;

    "OfficerRegistered(address,bytes32,uint256)": TypedContractEvent<
      OfficerRegisteredEvent.InputTuple,
      OfficerRegisteredEvent.OutputTuple,
      OfficerRegisteredEvent.OutputObject
    >;
    OfficerRegistered: TypedContractEvent<
      OfficerRegisteredEvent.InputTuple,
      OfficerRegisteredEvent.OutputTuple,
      OfficerRegisteredEvent.OutputObject
    >;

    "RequiredApprovalsUpdated(uint256,uint256,uint256)": TypedContractEvent<
      RequiredApprovalsUpdatedEvent.InputTuple,
      RequiredApprovalsUpdatedEvent.OutputTuple,
      RequiredApprovalsUpdatedEvent.OutputObject
    >;
    RequiredApprovalsUpdated: TypedContractEvent<
      RequiredApprovalsUpdatedEvent.InputTuple,
      RequiredApprovalsUpdatedEvent.OutputTuple,
      RequiredApprovalsUpdatedEvent.OutputObject
    >;

    "TransferRequestApproved(bytes32,address,uint256,uint256)": TypedContractEvent<
      TransferRequestApprovedEvent.InputTuple,
      TransferRequestApprovedEvent.OutputTuple,
      TransferRequestApprovedEvent.OutputObject
    >;
    TransferRequestApproved: TypedContractEvent<
      TransferRequestApprovedEvent.InputTuple,
      TransferRequestApprovedEvent.OutputTuple,
      TransferRequestApprovedEvent.OutputObject
    >;

    "TransferRequestCancelled(bytes32,address,uint256)": TypedContractEvent<
      TransferRequestCancelledEvent.InputTuple,
      TransferRequestCancelledEvent.OutputTuple,
      TransferRequestCancelledEvent.OutputObject
    >;
    TransferRequestCancelled: TypedContractEvent<
      TransferRequestCancelledEvent.InputTuple,
      TransferRequestCancelledEvent.OutputTuple,
      TransferRequestCancelledEvent.OutputObject
    >;

    "TransferRequestCreated(bytes32,bytes32,address,uint256)": TypedContractEvent<
      TransferRequestCreatedEvent.InputTuple,
      TransferRequestCreatedEvent.OutputTuple,
      TransferRequestCreatedEvent.OutputObject
    >;
    TransferRequestCreated: TypedContractEvent<
      TransferRequestCreatedEvent.InputTuple,
      TransferRequestCreatedEvent.OutputTuple,
      TransferRequestCreatedEvent.OutputObject
    >;

    "TransferRequestExecuted(bytes32,bytes32,address,uint256)": TypedContractEvent<
      TransferRequestExecutedEvent.InputTuple,
      TransferRequestExecutedEvent.OutputTuple,
      TransferRequestExecutedEvent.OutputObject
    >;
    TransferRequestExecuted: TypedContractEvent<
      TransferRequestExecutedEvent.InputTuple,
      TransferRequestExecutedEvent.OutputTuple,
      TransferRequestExecutedEvent.OutputObject
    >;
  };
}
